package com.mounir.openfacture.entities;

// Generated 15 mai 2011 17:36:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ArticleType generated by hbm2java
 */
public class ArticleType implements java.io.Serializable {

	private long id;
	private String code;
	private String description;
	private Set articles = new HashSet(0);

	public ArticleType() {
	}

	public ArticleType(long id) {
		this.id = id;
	}

	public ArticleType(long id, String code, String description, Set articles) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.articles = articles;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getArticles() {
		return this.articles;
	}

	public void setArticles(Set articles) {
		this.articles = articles;
	}

}
