package com.mounir.openfacture.entities;
// Generated 7 juin 2011 15:25:27 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ArticleType generated by hbm2java
 */
public class ArticleType  implements java.io.Serializable {


     private long id;
     private String code;
     private String description;
     private Set<Article> articles = new HashSet<Article>(0);

    public ArticleType() {
    }

    public ArticleType(String code, String description, Set<Article> articles) {
       this.code = code;
       this.description = description;
       this.articles = articles;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }




}


