package com.mounir.openfacture.entities;
// Generated 7 juin 2011 15:25:27 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DocumentType generated by hbm2java
 */
public class DocumentType  implements java.io.Serializable {


     private long id;
     private String code;
     private String description;
     private Set<Document> documents = new HashSet<Document>(0);

    public DocumentType() {
    }

	
    public DocumentType(long id) {
        this.id = id;
    }
    public DocumentType(long id, String code, String description, Set<Document> documents) {
       this.id = id;
       this.code = code;
       this.description = description;
       this.documents = documents;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Document> getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set<Document> documents) {
        this.documents = documents;
    }




}


