package com.mounir.openfacture.entities;

// Generated 15 mai 2011 17:36:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private long id;
	private String codeIso;
	private String name;
	private Set adresses = new HashSet(0);

	public Country() {
	}

	public Country(long id) {
		this.id = id;
	}

	public Country(long id, String codeIso, String name, Set adresses) {
		this.id = id;
		this.codeIso = codeIso;
		this.name = name;
		this.adresses = adresses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCodeIso() {
		return this.codeIso;
	}

	public void setCodeIso(String codeIso) {
		this.codeIso = codeIso;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Set adresses) {
		this.adresses = adresses;
	}

}
