package com.mounir.openfacture.entities;

// Generated 15 mai 2011 17:36:47 by Hibernate Tools 3.4.0.CR1

/**
 * FactureLine generated by hbm2java
 */
public class FactureLine implements java.io.Serializable {

	private long id;
	private Facture facture;
	private TvaType tvaType;
	private Article article;
	private Long lineNumber;
	private String description;
	private Long quantity;
	private Long unitPriceHt;
	private Long unitPriceTtc;
	private Long discountPct;
	private Long discountMntHt;
	private Long discountMntTtc;
	private Long totAmountHt;
	private Long totAmountTtc;

	public FactureLine() {
	}

	public FactureLine(long id) {
		this.id = id;
	}

	public FactureLine(long id, Facture facture, TvaType tvaType,
			Article article, Long lineNumber, String description,
			Long quantity, Long unitPriceHt, Long unitPriceTtc,
			Long discountPct, Long discountMntHt, Long discountMntTtc,
			Long totAmountHt, Long totAmountTtc) {
		this.id = id;
		this.facture = facture;
		this.tvaType = tvaType;
		this.article = article;
		this.lineNumber = lineNumber;
		this.description = description;
		this.quantity = quantity;
		this.unitPriceHt = unitPriceHt;
		this.unitPriceTtc = unitPriceTtc;
		this.discountPct = discountPct;
		this.discountMntHt = discountMntHt;
		this.discountMntTtc = discountMntTtc;
		this.totAmountHt = totAmountHt;
		this.totAmountTtc = totAmountTtc;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	public TvaType getTvaType() {
		return this.tvaType;
	}

	public void setTvaType(TvaType tvaType) {
		this.tvaType = tvaType;
	}

	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	public Long getLineNumber() {
		return this.lineNumber;
	}

	public void setLineNumber(Long lineNumber) {
		this.lineNumber = lineNumber;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	public Long getUnitPriceHt() {
		return this.unitPriceHt;
	}

	public void setUnitPriceHt(Long unitPriceHt) {
		this.unitPriceHt = unitPriceHt;
	}

	public Long getUnitPriceTtc() {
		return this.unitPriceTtc;
	}

	public void setUnitPriceTtc(Long unitPriceTtc) {
		this.unitPriceTtc = unitPriceTtc;
	}

	public Long getDiscountPct() {
		return this.discountPct;
	}

	public void setDiscountPct(Long discountPct) {
		this.discountPct = discountPct;
	}

	public Long getDiscountMntHt() {
		return this.discountMntHt;
	}

	public void setDiscountMntHt(Long discountMntHt) {
		this.discountMntHt = discountMntHt;
	}

	public Long getDiscountMntTtc() {
		return this.discountMntTtc;
	}

	public void setDiscountMntTtc(Long discountMntTtc) {
		this.discountMntTtc = discountMntTtc;
	}

	public Long getTotAmountHt() {
		return this.totAmountHt;
	}

	public void setTotAmountHt(Long totAmountHt) {
		this.totAmountHt = totAmountHt;
	}

	public Long getTotAmountTtc() {
		return this.totAmountTtc;
	}

	public void setTotAmountTtc(Long totAmountTtc) {
		this.totAmountTtc = totAmountTtc;
	}

}
