package com.mounir.openfacture.entities;

// Generated 15 mai 2011 17:36:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * LegalForm generated by hbm2java
 */
public class LegalForm implements java.io.Serializable {

	private long id;
	private String code;
	private String description;
	private Set companies = new HashSet(0);

	public LegalForm() {
	}

	public LegalForm(long id) {
		this.id = id;
	}

	public LegalForm(long id, String code, String description, Set companies) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.companies = companies;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set companies) {
		this.companies = companies;
	}

}
