package com.mounir.openfacture.entities;

// Generated 3 juin 2011 00:46:45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TvaType generated by hbm2java
 */
public class TvaType implements java.io.Serializable {

	private long id;
	private String code;
	private BigDecimal percentage;
	private Set<DocumentLine> documentLines = new HashSet<DocumentLine>(0);

	public TvaType() {
	}

	public TvaType(long id) {
		this.id = id;
	}
	
	public TvaType(long id, String code, BigDecimal percentage,
			Set<DocumentLine> documentLines) {
		this.id = id;
		this.code = code;
		this.percentage = percentage;
		this.documentLines = documentLines;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	public Set<DocumentLine> getDocumentLines() {
		return this.documentLines;
	}

	public void setDocumentLines(Set<DocumentLine> documentLines) {
		this.documentLines = documentLines;
	}

}
