package com.mounir.openfacture.entities;
// Generated 7 juin 2011 15:25:27 by Hibernate Tools 3.2.2.GA



/**
 * BankAccount generated by hbm2java
 */
public class BankAccount  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1298732974017923350L;
	
	private long id;
     private Adress adress;
     private String name;
     private String bankCode;
     private String office;
     private String accountNumber;
     private String ribKey;
     private String iban;
     private String bic;

    public BankAccount() {
    }

    public BankAccount(Adress adress, String name, String bankCode, String office, String accountNumber, String ribKey, String iban, String bic) {
       this.adress = adress;
       this.name = name;
       this.bankCode = bankCode;
       this.office = office;
       this.accountNumber = accountNumber;
       this.ribKey = ribKey;
       this.iban = iban;
       this.bic = bic;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Adress getAdress() {
        return this.adress;
    }
    
    public void setAdress(Adress adress) {
        this.adress = adress;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }
    public String getOffice() {
        return this.office;
    }
    
    public void setOffice(String office) {
        this.office = office;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public String getRibKey() {
        return this.ribKey;
    }
    
    public void setRibKey(String ribKey) {
        this.ribKey = ribKey;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public String getBic() {
        return this.bic;
    }
    
    public void setBic(String bic) {
        this.bic = bic;
    }




}


