package com.mounir.openfacture.entities;
// Generated 7 juin 2011 15:25:27 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private long id;
     private String codeIso;
     private String name;
     private Set<Adress> adresses = new HashSet<Adress>(0);

    public Country() {
    }

    public Country(String codeIso, String name, Set<Adress> adresses) {
       this.codeIso = codeIso;
       this.name = name;
       this.adresses = adresses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCodeIso() {
        return this.codeIso;
    }
    
    public void setCodeIso(String codeIso) {
        this.codeIso = codeIso;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Adress> getAdresses() {
        return this.adresses;
    }
    
    public void setAdresses(Set<Adress> adresses) {
        this.adresses = adresses;
    }




}


