package com.mounir.openfacture.entities;
// Generated 7 juin 2011 15:25:27 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TvaType generated by hbm2java
 */
public class TvaType  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8150879848603398361L;
	
	private long id;
     private String code;
     private BigDecimal percentage;
     private Set<DocumentLine> documentLines = new HashSet<DocumentLine>(0);

    public TvaType() {
    }

    public TvaType(String code, BigDecimal percentage, Set<DocumentLine> documentLines) {
       this.code = code;
       this.percentage = percentage;
       this.documentLines = documentLines;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public BigDecimal getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }
    public Set<DocumentLine> getDocumentLines() {
        return this.documentLines;
    }
    
    public void setDocumentLines(Set<DocumentLine> documentLines) {
        this.documentLines = documentLines;
    }




}


