package com.mounir.myfacture.entities;

// Generated 22 janv. 2013 22:17:16 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Encaissement generated by hbm2java
 */
public class Encaissement implements java.io.Serializable {

	private long id;
	private BankAccount bankAccount;
	private Date dtEncaissement;
	private BigDecimal montant;
	private String comment;

	public Encaissement() {
	}

	public Encaissement(long id) {
		this.id = id;
	}

	public Encaissement(long id, BankAccount bankAccount, Date dtEncaissement,
	    BigDecimal montant, String comment) {
		this.id = id;
		this.bankAccount = bankAccount;
		this.dtEncaissement = dtEncaissement;
		this.montant = montant;
		this.comment = comment;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public BankAccount getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(BankAccount bankAccount) {
		this.bankAccount = bankAccount;
	}

	public Date getDtEncaissement() {
		return this.dtEncaissement;
	}

	public void setDtEncaissement(Date dtEncaissement) {
		this.dtEncaissement = dtEncaissement;
	}

	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
