package com.mounir.myfacture.entities;

// Generated 7 d�c. 2012 11:57:47 by Hibernate Tools 4.0.0

/**
 * Facture generated by hbm2java
 */
public class Facture implements java.io.Serializable {

	private long id;

	public Facture() {
	}

	public Facture(long id) {
		this.id = id;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

}
