package com.mounir.myfacture.entities;

// Generated 7 d�c. 2012 11:57:47 by Hibernate Tools 4.0.0

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private long id;
	private TvaType tvaType;
	private Unit unit;
	private String code;
	private String description;
	private Long price;

	public Product() {
	}

	public Product(long id) {
		this.id = id;
	}

	public Product(long id, TvaType tvaType, Unit unit, String code,
			String description, Long price) {
		this.id = id;
		this.tvaType = tvaType;
		this.unit = unit;
		this.code = code;
		this.description = description;
		this.price = price;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public TvaType getTvaType() {
		return this.tvaType;
	}

	public void setTvaType(TvaType tvaType) {
		this.tvaType = tvaType;
	}

	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

}
