package com.mounir.myfacture.entities;

// Generated 7 d�c. 2012 11:57:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TvaType generated by hbm2java
 */
public class TvaType implements java.io.Serializable {

	private long id;
	private String code;
	private String description;
	private BigDecimal value;
	private Set<Product> products = new HashSet<Product>(0);

	public TvaType() {
	}

	public TvaType(long id) {
		this.id = id;
	}

	public TvaType(long id, String code, String description, BigDecimal value,
			Set<Product> products) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.value = value;
		this.products = products;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
