package com.mounir.myfacture.entities;

// Generated 7 d�c. 2012 11:57:47 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

	private long id;
	private String description;
	private String symbole;
	private Set<Product> products = new HashSet<Product>(0);

	public Unit() {
	}

	public Unit(long id) {
		this.id = id;
	}

	public Unit(long id, String description, String symbole,
			Set<Product> products) {
		this.id = id;
		this.description = description;
		this.symbole = symbole;
		this.products = products;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSymbole() {
		return this.symbole;
	}

	public void setSymbole(String symbole) {
		this.symbole = symbole;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
