package com.mounir.myfacture.entities.params;

// Generated 24 d�c. 2012 20:33:17 by Hibernate Tools 4.0.0

/**
 * Parameter generated by hbm2java
 */
public class Parameter implements java.io.Serializable {

	private ParameterId id;
	private String description;
	private String valueTxt;

	public Parameter() {
	}

	public Parameter(ParameterId id) {
		this.id = id;
	}

	public Parameter(ParameterId id, String description, String valueTxt) {
		this.id = id;
		this.description = description;
		this.valueTxt = valueTxt;
	}

	public ParameterId getId() {
		return this.id;
	}

	public void setId(ParameterId id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getValueTxt() {
		return this.valueTxt;
	}

	public void setValueTxt(String valueTxt) {
		this.valueTxt = valueTxt;
	}

}
