package com.mounir.openfacture.entities;
// Generated 7 juin 2011 15:25:27 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1152382195397734138L;
	
	private long id;
     private DocumentType documentType;
     private Currency currency;
     private Company company;
     private Set<DocumentLine> documentLines = new HashSet<DocumentLine>(0);

    public Document() {
    }

	
    public Document(long id) {
        this.id = id;
    }
    public Document(long id, DocumentType documentType, Currency currency, Company company, Set<DocumentLine> documentLines) {
       this.id = id;
       this.documentType = documentType;
       this.currency = currency;
       this.company = company;
       this.documentLines = documentLines;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public DocumentType getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }
    public Currency getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Set<DocumentLine> getDocumentLines() {
        return this.documentLines;
    }
    
    public void setDocumentLines(Set<DocumentLine> documentLines) {
        this.documentLines = documentLines;
    }




}


