package com.mounir.openfacture.entities;
// Generated 7 juin 2011 15:25:27 by Hibernate Tools 3.2.2.GA



/**
 * DocumentLine generated by hbm2java
 */
public class DocumentLine  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8874082085309777671L;
	
	private long id;
     private Document document;
     private TvaType tvaType;
     private Article article;
     private Long lineNumber;
     private String description;
     private Long quantity;
     private Long unitPriceHt;
     private Long unitPriceTtc;
     private Long discountPct;
     private Long discountMntHt;
     private Long discountMntTtc;
     private Long totAmountHt;
     private Long totAmountTtc;

    public DocumentLine() {
    }

	
    public DocumentLine(long id) {
        this.id = id;
    }
    public DocumentLine(long id, Document document, TvaType tvaType, Article article, Long lineNumber, String description, Long quantity, Long unitPriceHt, Long unitPriceTtc, Long discountPct, Long discountMntHt, Long discountMntTtc, Long totAmountHt, Long totAmountTtc) {
       this.id = id;
       this.document = document;
       this.tvaType = tvaType;
       this.article = article;
       this.lineNumber = lineNumber;
       this.description = description;
       this.quantity = quantity;
       this.unitPriceHt = unitPriceHt;
       this.unitPriceTtc = unitPriceTtc;
       this.discountPct = discountPct;
       this.discountMntHt = discountMntHt;
       this.discountMntTtc = discountMntTtc;
       this.totAmountHt = totAmountHt;
       this.totAmountTtc = totAmountTtc;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }
    public TvaType getTvaType() {
        return this.tvaType;
    }
    
    public void setTvaType(TvaType tvaType) {
        this.tvaType = tvaType;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Long getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(Long lineNumber) {
        this.lineNumber = lineNumber;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }
    public Long getUnitPriceHt() {
        return this.unitPriceHt;
    }
    
    public void setUnitPriceHt(Long unitPriceHt) {
        this.unitPriceHt = unitPriceHt;
    }
    public Long getUnitPriceTtc() {
        return this.unitPriceTtc;
    }
    
    public void setUnitPriceTtc(Long unitPriceTtc) {
        this.unitPriceTtc = unitPriceTtc;
    }
    public Long getDiscountPct() {
        return this.discountPct;
    }
    
    public void setDiscountPct(Long discountPct) {
        this.discountPct = discountPct;
    }
    public Long getDiscountMntHt() {
        return this.discountMntHt;
    }
    
    public void setDiscountMntHt(Long discountMntHt) {
        this.discountMntHt = discountMntHt;
    }
    public Long getDiscountMntTtc() {
        return this.discountMntTtc;
    }
    
    public void setDiscountMntTtc(Long discountMntTtc) {
        this.discountMntTtc = discountMntTtc;
    }
    public Long getTotAmountHt() {
        return this.totAmountHt;
    }
    
    public void setTotAmountHt(Long totAmountHt) {
        this.totAmountHt = totAmountHt;
    }
    public Long getTotAmountTtc() {
        return this.totAmountTtc;
    }
    
    public void setTotAmountTtc(Long totAmountTtc) {
        this.totAmountTtc = totAmountTtc;
    }




}


