package com.mounir.myfacture.entities;

// Generated 22 janv. 2013 22:17:16 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private long id;
	private String name;
	private String siren;
	private String siret;
	private String codeApe;
	private Long capital;
	private String url;
	private String tel;
	private String fax;
	private String mail;
	private Set<User> users = new HashSet<User>(0);
	private Set<BankAccount> bankAccounts = new HashSet<BankAccount>(0);

	public Company() {
	}

	public Company(long id) {
		this.id = id;
	}

	public Company(long id, String name, String siren, String siret,
	    String codeApe, Long capital, String url, String tel, String fax,
	    String mail, Set<User> users, Set<BankAccount> bankAccounts) {
		this.id = id;
		this.name = name;
		this.siren = siren;
		this.siret = siret;
		this.codeApe = codeApe;
		this.capital = capital;
		this.url = url;
		this.tel = tel;
		this.fax = fax;
		this.mail = mail;
		this.users = users;
		this.bankAccounts = bankAccounts;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSiren() {
		return this.siren;
	}

	public void setSiren(String siren) {
		this.siren = siren;
	}

	public String getSiret() {
		return this.siret;
	}

	public void setSiret(String siret) {
		this.siret = siret;
	}

	public String getCodeApe() {
		return this.codeApe;
	}

	public void setCodeApe(String codeApe) {
		this.codeApe = codeApe;
	}

	public Long getCapital() {
		return this.capital;
	}

	public void setCapital(Long capital) {
		this.capital = capital;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<BankAccount> getBankAccounts() {
		return this.bankAccounts;
	}

	public void setBankAccounts(Set<BankAccount> bankAccounts) {
		this.bankAccounts = bankAccounts;
	}

}
