package com.mounir.myfacture.entities;

// Generated 22 janv. 2013 22:17:16 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private long id;
	private Company company;
	private String firstName;
	private String lastName;
	private String login;
	private String password;
	private String mail;
	private Date birthDate;
	private String phone;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(long id, Company company, String firstName, String lastName,
	    String login, String password, String mail, Date birthDate, String phone) {
		this.id = id;
		this.company = company;
		this.firstName = firstName;
		this.lastName = lastName;
		this.login = login;
		this.password = password;
		this.mail = mail;
		this.birthDate = birthDate;
		this.phone = phone;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
